Add missing test annotations
m4tthumphrey/php-gitlab-api pull request #568
Opened 2020-08-17 16:50 UTC by lboynton

These tests weren't being run!

2020-08-17 18:45 UTC, GrahamCampbell commented
Please could you send this to 19.9. :)

2020-08-17 18:46 UTC, GrahamCampbell requested changes

2020-08-17 18:46 UTC, GrahamCampbell commented on tests/Api/ProjectsTest.php
>      public function shoudGetApprovalRules(): void
`shoudGetApprovalsRules`

2020-08-17 18:59 UTC, lboynton commented on tests/Api/ProjectsTest.php
>      public function shoudGetApprovalRules(): void
Done :)

2020-08-17 19:00 UTC, lboynton commented
> Please could you send this to 19.9. :)

Rebased on 9.19, hope that's correct :)

2020-08-17 19:55 UTC, GrahamCampbell commented
Yep, this looks great. :+1:

2020-08-17 19:55 UTC, merged

2020-08-18 07:05 UTC, glensc commented
I find it more convenient to use matching pattern for method names: `testSomething`, so they get picked up automatically. less clutter as well.