Get Groups Merge Requests
m4tthumphrey/php-gitlab-api pull request #671
Opened 2021-11-08 12:25 UTC by alexbowers

2021-11-11 13:01 UTC, 20uf approved these changes

2021-12-26 15:58 UTC, GrahamCampbell requested changes

2021-12-26 15:58 UTC, GrahamCampbell commented on src/Api/Groups.php
> +    public function mergeRequests($group_id, array $parameters = [])
Please add phpdoc for this method, like the others.

2022-01-23 16:05 UTC, GrahamCampbell commented
Closing due to inactivity. Please feel free to send in a new PR if you'd still like for this change to be made.

2022-01-23 16:05 UTC, closed without merging