Projects: add method to fetch all groups the projects is shared with
m4tthumphrey/php-gitlab-api pull request #673
Opened 2021-11-10 11:40 UTC by glaubinix

https://docs.gitlab.com/ee/api/projects.html#list-a-projects-groups

2021-11-10 12:21 UTC, 20uf approved these changes

2021-12-26 15:59 UTC, GrahamCampbell requested changes

2021-12-26 15:59 UTC, GrahamCampbell commented on src/Api/Projects.php
> +     * @param array      $parameters
Please either remove this parameter or add proper doc and the options resolver.

2022-01-23 16:05 UTC, GrahamCampbell commented
Closing due to inactivity. Please feel free to send in a new PR if you'd still like for this change to be made.

2022-01-23 16:05 UTC, closed without merging