Added upload avatar method.
m4tthumphrey/php-gitlab-api pull request #681
Opened 2021-12-22 12:12 UTC by DukeW

Recently migrated to GitLab from SVN. Most of our projects have a project icon at a specific path in the repo, needed an automatic way of uploading these icons to GitLab.

2021-12-26 19:19 UTC, GrahamCampbell requested changes
Please add test coverage for this. Then, I'll be happy to accept.

2021-12-28 13:00 UTC, DukeW commented
Added a test. It is my first time doing any kind of unit testing in PHP or on a REST API, so I have no idea if I did it right. Let me know, thanks.

2021-12-29 11:44 UTC, GrahamCampbell commented
NB It's not intended that you enable StyleCI on forks. StyleCI can apply the fixes when this PR is merged.

2021-12-30 01:15 UTC, TecsiAron commented
Cleaned up the commits.
Let me know if any further changes are needed. 
(I ran StyleCI on the fork because I got an error on my original commit stating that the formatting is wrong.)

2021-12-30 08:43 UTC, 20uf approved these changes

2022-01-23 16:03 UTC, GrahamCampbell commented
> I ran StyleCI on the fork because I got an error on my original commit stating that the formatting is wrong.

It is still not necessary to do this.

2022-01-23 16:03 UTC, merged

2022-01-23 16:03 UTC, GrahamCampbell commented
Thanks for the PR.