[12.0] Add support for prefixed URIs on base path
m4tthumphrey/php-gitlab-api pull request #726
Opened 2022-10-17 13:01 UTC by abelharisov

Support custom gitlab installations with url like host/some/path/to/gitlab

2023-03-06 12:00 UTC, GrahamCampbell commented
Thanks for the PR. I feel that this is a breaking change, so I think we need to delay this until a v12.0.0 release.

2023-03-23 13:12 UTC, GrahamCampbell requested changes

2023-03-23 13:12 UTC, GrahamCampbell commented on src/Api/Projects.php
> +    public function removeTrigger($project_id, int $trigger_id)
Please remove this change.

2023-03-23 14:08 UTC, sklmx commented on src/Api/Projects.php
> +    public function removeTrigger($project_id, int $trigger_id)
fixed

2023-07-26 11:02 UTC, GrahamCampbell commented
not stale

2023-12-15 03:31 UTC, GrahamCampbell commented
Not stale

2024-03-20 09:29 UTC, GrahamCampbell commented
This PR is still in consideration for the next major version.

2024-04-10 19:49 UTC, datawench commented
Any thoughts on when this might become current? I happen to have a project that has a nonstandard self-hosted path (it's like `gitlab.myproject.com/gitlab`), and it's taken me a while to track down that this is why the `host` attribute of the request's URI gets hosed.

2025-02-23 16:56 UTC, closed without merging