[11.13] Repository branch and file check existence methods
m4tthumphrey/php-gitlab-api pull request #782
Opened 2023-10-31 13:42 UTC by misantron

2023-11-13 10:26 UTC, misantron commented
Hello, take a look please

2023-12-03 22:29 UTC, GrahamCampbell requested changes
These changes don't seem work properly. Instead of returning false if not exists, this actually throw an exception. We are, critically, missing tests for that case.

2023-12-04 07:38 UTC, misantron commented
```
try {
   $this->head($uri, []);
            
   return true;
} catch (Gitlab\Exception\RuntimeException $ex) {
   if (404 === $ex->getCode()) {
      return false;
   }
   throw $ex;
}
 ```
 @GrahamCampbell can I use such a code to handle exception and check entity existence?

2025-01-23 05:56 UTC, misantron commented
the question is still actual

2025-02-23 16:56 UTC, closed without merging